### ISSUE TITLE
Alternative docker deployment option

### ISSUE THREAD

**Issue by DaphneINOPIA** [pigzillaaaaa/daddylive#18]
### Deploying Dockerfile on Render
_Links Render app with your fork, automatically deploying when your fork updates_
1. Fork this repo
2. Go to https://render.com/ and create an account using your GitHub account
3. On your **Dashboard**, click **New +** → **Web Service** → **Deploy from Github**
4. Select your forked `daddylive` repo
5. Use the following settings:
- Language: Docker
- Branch: main
- Region: choose the closest region to your location
- Root Directory: leave empty
- Dockerfile Path: leave empty (autodetects Dockerfile in your repo)
- Instance Type: Free
- Environment Variables: leave empty
- Advanced: leave untouched 
6. Click **Deploy Web Service** and wait for it to deploy
7. Go to your project's **Settings** and make sure **Auto-Deploy** is set to **On Commit**
8. Find your project's link at the top of your project's Dashboard page and add `/playlist/channels/` at the end of it to have your channel's playlist link to be used in your IPTV app

### Preventing Web Service from sleeping with UptimeRobot
_Pings your Render app every 5 minutes, keeping your app running 24/7_
1. Go to https://uptimerobot.com/ and create an account
2. Click on *New Monitor +*
3. Use the following settings:
- Monitor Type: HTTP(s)
- URL to monitor: your Render project link
- How will we notify you?: if you want notifications, choose your preferred type
- Monitor Interval: 5 minutes
4. Click on **Create Monitor**

### Upstream Sync Workflow with GitHub Action
_Keeps your repo synced with pigzillaaaaa's automatically on a schedule_
1. Go to your forked Github repo 
2. Click on **Code** → **+** → **+ Create New File**
3. In the Name your file box type `.github/workflows/sync-upstream.yml`
4. Paste the following code in the file you just created:
```
name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add Upstream Repo
        run: git remote add upstream https://github.com/pigzillaaaaa/daddylive.git

      - name: Fetch and Merge Upstream
        run: |
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories --no-edit || true
          git push origin main

```
5. Click on **Commit changes...** → **Commit changes**
6. Click on **Actions** → **Sync Upstream** → **Run workflow** to test if it runs successfully

- [x] Done

**Comment by GitLatte** [comment]
@DaphneINOPIA thanks. Really works as expected.

But I want to add some details about this processings.

You don't need to fork whole repository to make it work. Only Dockerfile is enough.

With your process steps, we choose On-Commit for Auto Deploy. So that means each commit for main branch will trigger for Auto Deploy. There is a line in Dockerfile that git clone ... Which means every deploy will clone the newest version of pigzillaaaaa's daddylive repository's new version with changes which are different than previous deploy.

By this way, if you add a workflow file which pushes some commits on main branch for ex: changing a line in a simple text file or readme.md will make the auto deploy. Also your upstream sync workflow action will trigger to auto deploy for every 1 hours which means if we use free plan on render.com the sources which are limited are under some risks.
Also we can't be sure how much time the deploy will take so that may cause an outage of 5/10/15 minutes or more for every 1 hour. Especially for free Pipeline Minutes limits which are 500 minutes making it in every hours.

Quick calculation for 5 minute deploy time makes 3600 minutes if we force it to auto deploy which means exceeding free 500 minutes pipeline limits.
But if we trigger it to auto deploy in 12 hours with 5 minutes deploy time that makes about 300 minutes. We can only use our right for up to 300 minutes within our 500 minutes limits.

Let's make it 10 minutes to auto deploy that means 7200 minutes.
12 hours makes it 600 > 500.

In order to stay within our 500-minute limits, my suggestion is to trigger the workflow file to run at least once every 12 hours. In this way, we can stay within our monthly 500-minute limit by anticipating a maximum deployment time of 5-10 minutes. We already have 100 GB of traffic per month. At least for individual users, we can push our limits to stay within all free limits, but we should also eliminate the possibility of being left halfway.

Http website monitoring works for keep it alive, yes. We can push commits for every 6 hours (for 3 minutes deploy) or 12 hours (for 5 minutes deploy) to keep it updated with pigzillaaaaa's repository and keep limited resources's lifetime.

Check out my repository [render](https://github.com/GitLatte/render)

I checked the deploy time after my workflow run to test it and it took about 3 minutes to finish. Second attempt took 1.5 minutes. But accepting it for 5 minutes to prepare workflow file for auto deploy (for some delays) is the safest way I think. 

Fork this repository or copy all the files whichever method you want to use is up to you.
Add new Web Service
Choose Github and select the repository which is same as mine.

The YAML in my repository set up for work in every 8 hours.
Will change the README.md file with the new update time like: Last automatic update trigger: Sun Jun 1 01:35:53 UTC 2025

If you use web monitoring with uptimerobot and keep it alive;
the files will upload the service on render and make it auto deploy.
Each new auto deploy will clone pigzillaaaaa's repository by Dockerfile content.

![Image](https://github.com/user-attachments/assets/f556b59d-26fe-4a3f-9ab7-5dde1bf1fea1)

If what I have written and tried to explain seems complicated, please do not hesitate to ask.

I'm grateful with your help and pigzillaaaaa's useful file system to find another way to make it work.

**Comment by jimmyoffa** [comment]
Vercel also have the same time and bandwith limit: 500-minute limits/100 GB of traffic per month, like with Render?

@GitLatte @pigzillaaaaa

**Comment by jimmyoffa** [comment]
> > 1. Vercel also have the same time and bandwith limit: 500-minute limits/100 GB of traffic per month, like with Render?
> > 2. For Vercel and Render there is not need to set the two secrets SPACE_NAME and TOKEN like with HF
> > 
> > [@GitLatte](https://github.com/GitLatte) [@pigzillaaaaa](https://github.com/pigzillaaaaa)
> 
> Right and thanks for additional server information [@jimmyoffa](https://github.com/jimmyoffa) 🖐️ Steps we do are for keeping them alive. For render with uptimerobot ping to web server makes it keep alive else it goes to sleep within 15 minutes. And auto commit to repository like for each 12 hours keeps the root pigzillaaaaa's repository updated with web server.
> 
> Not sure for vercel but you are probably right it too.
> 
> Difference for huggingface we do rebuild to keep it updated with this repository. There is no need to use any GitHub repository to make it work, only the Dockerfile all we need. We just use our repositories with tokens for auto factory rebuild for unaccepted errors and updated root repo contents.
> 
> All free and limited servers needs different processing steps with this project.
> 
> Actually for render and vercel the 100 GB monthly traffic limit is not enough if we use the m3u8 file contents long time to watch. Not all are 1080p or higher but have to check for one how much data it takes for an hour.
> 
> I'm not sure and couldn't find a right document for huggingface but read in somewhere that says the limit resets hourly with rebuild.
> 
> Also I used and tested with one of my friend and we got same results: The list items (channels) with render web server runs faster than huggingface space. Not long caching or loading time after you open a channel and it's really way faster 🤟😅

If Render and Vercel have the same limit of time and bandwith honestly i prefer to stay with HF also if this last is slower :(

**Comment by jimmyoffa** [comment]
@GitLatte Hi friend, i need to talk with you in private, not for this issue obviously.
How?

**Comment by GitLatte** [comment]
> > > [@GitLatte](https://github.com/GitLatte) Please can you make a simple guide like you done with the previous hf-docker but for render: https://github.com/GitLatte/render/tree/main
> > > It's not clear to me, especially the part about the github token..
> > > Ps. i remember the render space automatically deploy an rebuild if the space sees a change in the github repo. So my question is: the https://github.com/GitLatte/render/tree/main is really needed?
> > 
> > 
> > Ah sure.
> > We don't use tokens for this render repository.
> > Steps are all easy.
> > If you fork it or create your own you'll have same files like mine. Let's continue if you fork it:
> > 
> > 1. No need to change anything on repository except the cron time to your needs if you want.
> > 2. Go to render and select web service. (A new account or only one web service for this should be best option)
> > 3. Select GitHub and select the repository you want to deploy. For this it will be render repository.
> > 4. After deploy it'll be done.
> > 5. Go to uptimerobot.com and add your render address to web monitor to keep it alive.
> > 6. Go to your repository and make your first run if you want to rebuild it or wait for scheduled run after xx hours which is in workflow file (update.yml)
> > 
> > Uptimerobot web monitor will ping it every 5 minutes so it'll block to set sleeping for your web service on render.
> > Forked repository's workflow will commit the update time to readme.md file so that will trigger to render web service for auto deploy. Because setting on commit option when you create the render web service means any commit on main branch will trigger the auto deploy. So we don't do anything special but changing update time on readme.md file which is on main branch helps us to make it auto deploy for cloning this repository with latest content on it.
> > That's all.
> 
> Where is the render repo? cant seem to find it.

Create a new repository.

Add the Dockerfile into main branch.
Add a Readme.md file into main branch.

create .github/workflows/update.yml file with this content:

```
# This workflow updates the README.md file with the latest timestamp to trigger Render auto-deploy
name: Trigger Render Deploy (Overwrite README)

on:
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours (at minute 0 past every 8th hour)
  workflow_dispatch:        # Allows manual trigger from GitHub Actions tab

permissions:
  contents: write # Grant permissions to write to the repository

jobs:
  update_readme:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Checkout your repository code

      - name: Configure Git
        run: |
          # Configure Git with bot user details
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Overwrite README.md with latest timestamp
        run: |
          # Overwrite README.md with only the latest update timestamp
          echo "Last automatic update trigger: $(date)" > README.md # Use '>' to overwrite

      - name: Commit and Push Changes
        run: |
          # Add the modified README.md file to staging
          git add README.md
          # Check if there are any changes staged for commit
          # If there are changes, commit them
          # The || true at the end prevents the workflow from failing if there are no changes
          git diff --quiet --cached || git commit -m "Automated README update to trigger deploy"
          # Push the changes to the main branch
          # Assumes your main branch is named 'main'
          git push origin main
        env:
          # Use the default GITHUB_TOKEN for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Go to render.com and login with your Github account.
Click New and Web Service.
Choose your github repository to deploy which you created with theese files.


Your playlists will now work on render.com and with this codes and yml codes your readme.md file will change with a new timestamp in every 8 hours and it will commit to main branch and that will make new deploy on render.

But don't remember to add your render web service address to uptimerobot to make it keep up always. Else it'll go to sleeping mode after 15 minutes.
