### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by newf276** [pigzillaaaaa/daddylive#9]
Hey thanks pigzillaaaa, great idea for HF WS.

Is it possible for me to be able to just pull the ice hockey events and nothing else, no channels, or other groups?  If so, perhaps you could give me a hint. on how to accomplish.

If it is not possible, thanks again.

newf276

**Comment by GitLatte** [comment]
You can use a workflow to fetch and create/update from your events list address.

First in your repository create a file name with ih_filter.yml (or whatever you want) in .github/workflows dir.

Then copy/paste this code below.
Change the URL address which I wrote with place here your events url in the codes. 
Commit and go Actions tab for enable/trigger this file.

After first run it will crate ice-hockey-events.m3u file in your main dir. Will be updated in every 6 hours.
You can change the file name in codes.

Now you can use the raw address of the new file for watch only events which have ice hockey group title.

Enjoy it.

```
name: Filter ICE HOCKEY Events
on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  filter-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download full event list
        run: curl -L -o original.m3u "PLACE-HERE-YOUR-EVENTS-URL"

      - name: Convert file to UTF-8
        run: iconv -f ISO-8859-1 -t UTF-8 original.m3u -o original_utf8.m3u

      - name: Extract ICE HOCKEY events
        run: |
          echo "#EXTM3U" > ice-hockey-events.m3u
          grep -A 1 -i 'group-title="ICE HOCKEY"' original_utf8.m3u | grep -v -- "^--$" >> ice-hockey-events.m3u

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ice-hockey-events.m3u
          git commit -m "Fetched and Updated ICE HOCKEY events"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
